# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Computer Science
tagline:          SCLS
description:      '<p> Derek Hu </p> <p> tong.hu@scls-sh.org </p>'
url:              http://hyde.getpoole.com
baseurl:          https://scls-cs.github.io/2020/

author:
  name:           'Derek'
  url:            tong.hu@scls-sh.org

paginate:         5
